import test from "node:test";
import assert from "node:assert/strict";
import {execFileSync} from "node:child_process";
import {readFile,readdir} from "node:fs/promises";
import {createHash} from "node:crypto";
import {resolve} from "node:path";
test("hosting build copies only manifested runtime and public evidence",async()=>{
  const dest=execFileSync("node",["hosting/build.mjs"],{encoding:"utf8"}).trim();
  const manifest=JSON.parse(await readFile(resolve(dest,"deployment-manifest.json"),"utf8"));
  const paths=manifest.files.map(f=>f.path);
  for(const file of manifest.files){
    const bytes=await readFile(resolve(dest,file.path));
    assert.equal(createHash("sha256").update(bytes).digest("hex"),file.sha256);
    assert.doesNotMatch(file.path,/(private|journal|accounts|__pycache__|\.env|harness|server\.py|test_)/i);
  }
  assert.ok(paths.includes("public/index.html"));
  assert.ok(paths.includes("api/dispatch.py"));
  assert.ok(paths.includes("public/proof-model.js"));
  assert.ok(paths.includes("public/workspace.html"));
  assert.ok(paths.includes("public/workspace-model.js"));
  assert.ok(paths.includes("public/wallet-discovery.js"));
  assert.ok(paths.includes("public/InterVariable.woff2"));
  assert.ok(paths.includes("public/Inter-LICENSE.txt"));
  assert.ok(paths.includes("public/recall-logo.png"));
  assert.ok(paths.includes("public/recall-mark.png"));
  assert.ok(paths.includes("public/brand.css"));
  assert.deepEqual(await readFile(resolve(dest,"public/recall-mark.png")),await readFile("submission/recall-logo.png"));
  for(const page of ["workspace","proof","index","purchase","recorded"]){
    const html=await readFile(resolve(dest,"public/"+page+".html"),"utf8");
    assert.match(html,/rel="icon" href="\/recall-mark.png"/);
    assert.match(html,/class="brand-mark" src="\/recall-mark.png" width="26" height="26" alt=""/);
    assert.match(html,/href="\/brand.css"/);
    assert.doesNotMatch(html.match(/<a class="brand"[\s\S]*?<\/a>/)[0],/class="brand-dot"|↶/);
  }
  assert.deepEqual(await readFile(resolve(dest,"public/recall-logo.png")),await readFile("submission/recall-logo.png"));
  assert.equal((await readFile(resolve(dest,"public/InterVariable.woff2"))).subarray(0,4).toString(),'wOF2');
  assert.match(await readFile(resolve(dest,"public/Inter-LICENSE.txt"),'utf8'),/SIL OPEN FONT LICENSE/);
  assert.match(await readFile(resolve(dest,"public/workspace.css"),'utf8'),/src:url\('\/InterVariable.woff2'\)/);
  assert.ok(paths.includes("public/proof.html"));
  assert.ok(!paths.includes("server.py"));
  assert.deepEqual((await readdir(resolve(dest,"live"))).sort(),["full-flow-report.json","wallet-run-2026-09-07.json"]);
  const config=JSON.parse(await readFile(resolve(dest,"vercel.json"),"utf8"));
  assert.equal(config.framework,null);
  assert.equal(config.outputDirectory,"public");
  assert.equal(config.rewrites,undefined);
  assert.equal(config.functions["api/**/*.py"].maxDuration,60);
  assert.match(config.headers[0].headers.find(h=>h.key==='Content-Security-Policy').value,/font-src 'self';/);
  const csp=config.headers[0].headers.find(h=>h.key==='Content-Security-Policy').value;
  assert.match(csp,/img-src 'self' data:;/);
  assert.match(csp,/script-src 'self';/);
  assert.match(csp,/connect-src 'self';/);
  assert.equal(paths.filter(p=>p.startsWith("api/")).length,11);
  assert.ok(paths.includes("api/catalog/check.py"));
  assert.ok(paths.includes("catalog_sources.py"));
  assert.ok(paths.includes("public/service-catalog.json"));
  assert.deepEqual(await readFile(resolve(dest,"public/index.html")),await readFile("ui/compare.html"));
  assert.deepEqual(await readFile(resolve(dest,"public/proof.html")),await readFile("ui/proof.html"));
  assert.ok(paths.includes("commerce_flow.py"));
  assert.ok(paths.includes("contracts/recall_purchase.py"));
  assert.ok(paths.includes("api/session/receipt.py"));
});
