import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {WalletPreference,WalletRestorer,WALLET_CHOICE_KEY} from '../ui/wallet-session.js';
import {DISCONNECT_KEY,registerWallet} from '../ui/wallet-discovery.js';
import {WalletConnection} from '../ui/wallet-connection.js';
const account='0x'+'1'.repeat(40),other='0x'+'2'.repeat(40);
function storage(){const data=new Map([['recall.provider-reviews.v1','saved evidence'],['recall.commerce.v2','pending transaction']]);return {data,getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)};}
function entry(rdns='io.rabby',read=async()=>[account]){const calls=[],listeners=new Map(),provider={request:args=>{calls.push(args.method);return read(args);},on:(e,f)=>{if(!listeners.has(e))listeners.set(e,new Set());listeners.get(e).add(f);},removeListener:(e,f)=>listeners.get(e)?.delete(f),emit:(e,value)=>{for(const f of listeners.get(e)||[])f(value);}};return {rdns,name:'Test wallet',provider,calls,listeners};}
function setup(entries=[entry()]){const store=storage(),preference=new WalletPreference(store),providers=new Map(entries.map((e,i)=>[i,e])),applied=[];return {store,preference,providers,applied,restorer:new WalletRestorer(preference,providers,(e,a)=>applied.push({entry:e,account:a}))};}
test('fresh visits do not query any installed wallet',async()=>{const x=setup();assert.equal(await x.restorer.attempt(),false);assert.equal(x.providers.get(0).calls.length,0);});
test('refresh restores only the previously selected provider using eth_accounts',async()=>{const a=entry('io.first'),b=entry('io.selected'),x=setup([a,b]);x.preference.remember(b);const fresh=new WalletPreference(x.store),r=new WalletRestorer(fresh,x.providers,(e,a)=>x.applied.push({entry:e,account:a}));assert.equal(await r.attempt(),true);assert.equal(x.applied[0].entry,b);assert.equal(x.applied[0].account,account);assert.deepEqual(a.calls,[]);assert.deepEqual(b.calls,['eth_accounts']);assert.deepEqual(JSON.parse(x.store.getItem(WALLET_CHOICE_KEY)),{kind:'rdns',id:'io.selected'});assert.equal(x.store.getItem('recall.provider-reviews.v1'),'saved evidence');assert.equal(x.store.getItem('recall.commerce.v2'),'pending transaction');assert.ok(!x.store.getItem(WALLET_CHOICE_KEY).includes(account));});
test('provider UUID changes across navigation do not change selected wallet',async()=>{const x=setup([]),first=entry();x.preference.remember(first);registerWallet(x.providers,{info:{uuid:'new-uuid-for-new-page',rdns:'io.rabby',name:'Rabby'},provider:first.provider});assert.equal(await x.restorer.attempt(),true);assert.equal(x.applied[0].entry.provider,first.provider);});
test('unknown selection and ambiguous identity never fall back to another wallet',async()=>{for(const entries of [[entry('io.other')],[entry(),entry()]]){const x=setup(entries);x.preference.remember(entry());assert.equal(await x.restorer.attempt(),false);assert.ok(entries.every(e=>e.calls.length===0));}});
test('late provider announcements can restore; duplicate announcements do not repeat account queries',async()=>{const x=setup([]),selected=entry();x.preference.remember(selected);assert.equal(await x.restorer.attempt(),false);x.providers.set('late',selected);assert.equal(await x.restorer.attempt(),true);assert.equal(await x.restorer.attempt(),false);assert.deepEqual(selected.calls,['eth_accounts']);});
test('explicit disconnect survives a new page and leaves records and permissions alone',async()=>{const x=setup(),selected=x.providers.get(0);x.preference.remember(selected);x.preference.disconnect();const r=new WalletRestorer(new WalletPreference(x.store),x.providers,()=>assert.fail('restored after disconnect'));assert.equal(await r.attempt(),false);assert.deepEqual(selected.calls,[]);assert.equal(x.store.getItem(DISCONNECT_KEY),'true');assert.equal(x.store.getItem(WALLET_CHOICE_KEY),undefined);assert.equal(x.store.getItem('recall.commerce.v2'),'pending transaction');x.preference.remember(selected);assert.equal(await x.restorer.attempt(),true);});
test('locked, revoked, invalid, rejected account reads never prompt or show cached identity',async()=>{for(const response of [[],null,{},['bad'],['0x'+'0'.repeat(40)]]){const e=entry('io.rabby',async()=>response),x=setup([e]);x.preference.remember(e);assert.equal(await x.restorer.attempt(),false);assert.equal(x.applied.length,0);assert.deepEqual(e.calls,['eth_accounts']);}const e=entry('io.rabby',async()=>{throw Error('locked');}),x=setup([e]);x.preference.remember(e);assert.equal(await x.restorer.attempt(),false);});
test('a manual disconnect or wallet switch invalidates an outstanding restore',async()=>{for(const change of ['disconnect','choose']){let resolve;const e=entry('io.rabby',()=>new Promise(r=>resolve=r)),x=setup([e]);x.preference.remember(e);const pending=x.restorer.attempt();await Promise.resolve();if(change==='disconnect')x.preference.disconnect();else{x.preference.cancel();x.preference.remember(entry('io.different'));}resolve([account]);assert.equal(await pending,false);assert.equal(x.applied.length,0);}});
test('account, chain and provider changes while restoring reject stale responses',async()=>{for(const event of ['accountsChanged','chainChanged','disconnect']){let resolve;const e=entry('io.rabby',()=>new Promise(r=>resolve=r)),x=setup([e]);x.preference.remember(e);const pending=x.restorer.attempt();await Promise.resolve();e.provider.emit(event,[]);resolve([account]);assert.equal(await pending,false);assert.equal(x.applied.length,0);assert.ok([...e.listeners.values()].every(set=>set.size===0));}});
test('restore reads the current authorized account, never a saved address',async()=>{const e=entry('io.rabby',async()=>[other]),x=setup([e]);x.preference.remember(e);assert.equal(await x.restorer.attempt(),true);assert.equal(x.applied[0].account,other);});
test('denied or corrupted storage fails closed while explicit connection remains available',async()=>{const denied={getItem(){throw Error('denied');},setItem(){throw Error('denied');},removeItem(){throw Error('denied');}},e=entry(),p=new WalletPreference(denied);assert.equal(p.remember(e),false);assert.equal(p.read(),null);assert.equal(p.disconnect(),false);const connection=new WalletConnection();assert.equal(await connection.connect(e.provider),true);for(const raw of ['oops','{}','{"kind":"rdns","id":"invalid"}','{"kind":"rdns","id":"io.rabby","account":"x"}']){const s=storage();s.setItem(WALLET_CHOICE_KEY,raw);assert.equal(new WalletPreference(s).read(),null);}});
test('unbranded ambiguous legacy wallets are not guessed; recognized flags retain preference',async()=>{const x=setup(),e=x.providers.get(0);delete e.rdns;x.preference.remember(e);assert.equal(await x.restorer.attempt(),false);e.provider.isRabby=true;e.provider.isMetaMask=true;x.preference.remember(e);assert.deepEqual(x.preference.read(),{kind:'legacy',id:'isRabby'});assert.equal(await x.restorer.attempt(),true);});
test('page disposal and back-forward suspension invalidate pending results',async()=>{for(const action of ['dispose','pause']){let resolve;const e=entry('io.rabby',()=>new Promise(r=>resolve=r)),x=setup([e]);x.preference.remember(e);const pending=x.restorer.attempt();await Promise.resolve();x.restorer[action]();resolve([account]);assert.equal(await pending,false);assert.equal(x.applied.length,0);}});
test('a flow becoming busy during restoration prevents adopting an identity',async()=>{let resolve,ready=true;const e=entry('io.rabby',()=>new Promise(r=>resolve=r)),x=setup([e]);x.preference.remember(e);x.restorer.eligible=()=>ready;const pending=x.restorer.attempt();await Promise.resolve();ready=false;resolve([account]);assert.equal(await pending,false);assert.equal(x.applied.length,0);});
test('a broken extension listener cleanup does not reject page restoration',async()=>{const x=setup(),e=x.providers.get(0);e.provider.removeListener=()=>{throw Error('Extension cleanup unavailable');};x.preference.remember(e);assert.equal(await x.restorer.attempt(),true);assert.equal(x.applied.length,1);});
test('adopting a fresh authorized account attaches events without asking permission again',()=>{const e=entry(),c=new WalletConnection();assert.equal(c.adopt(e.provider,account),true);assert.deepEqual(e.calls,[]);e.provider.emit('accountsChanged',[other]);assert.equal(c.account,other);e.provider.emit('accountsChanged',[]);assert.equal(c.account,null);assert.equal(c.adopt(e.provider,'bad'),false);});
test('restoration code cannot sign, prepare, request permissions, switch networks, or persist an account',()=>{const source=readFileSync('ui/wallet-session.js','utf8');assert.doesNotMatch(source,/eth_requestAccounts|eth_sendTransaction|personal_sign|eth_sign|wallet_switch|wallet_add|fetch\(|localStorage/);assert.match(source,/method:'eth_accounts'/);});
